image: node:14-alpine

cache:
  key: ${CI_COMMIT_SHORT_SHA}
  paths:
    - .yarn
    - dist/
    - node_modules/
    - public/
    - .cache/

variables:
  AWS_DEFAULT_REGION: us-west-2

stages: 
  - build-develop
  - build-production
  - s3-upload-develop
  - s3-upload-production

build-develop:
  stage: build-develop
  environment:
    name: develop
  only:
    - develop
  script:
    - yarn install
    - yarn build
  artifacts:
    name: ${CI_COMMIT_SHORT_SHA}-${CI_COMMIT_BRANCH}
    paths:
      - public/
  cache:
    key: ${CI_COMMIT_SHORT_SHA}-${CI_COMMIT_BRANCH}
    paths:
      - dist/
      - node_modules/
      - public/
      - .cache/
  only:
    refs:
      - develop

build-production:
  stage: build-production
  environment:
    name: production
  only:
    - production
  script:
    - yarn install
    - yarn build
  artifacts:
    name: ${CI_COMMIT_SHORT_SHA}-${CI_COMMIT_BRANCH}
    paths:
      - public/
  cache:
    key: ${CI_COMMIT_SHORT_SHA}-${CI_COMMIT_BRANCH}
    paths:
      - dist/
      - node_modules/
      - public/
      - .cache/
  only:
    refs:
      - main
      - master

s3-upload-develop:
  stage: s3-upload-develop
  image:
     name: banst/awscli
     entrypoint: [""]
  environment:
    name: develop
  script:
    - cd public
    - echo S3 Bucket - $S3_BUCKET
    - echo Cloudfront Distribution ID - $CLOUDFRONT_ID
    - aws s3 rm s3://$S3_BUCKET/ --recursive
    - aws s3 sync ./ s3://$S3_BUCKET/
    - export AWS_MAX_ATTEMPTS="2"
    - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"
  only:
    refs:
      - develop

s3-upload-production:
  stage: s3-upload-production
  image:
     name: banst/awscli
     entrypoint: [""]
  environment:
    name: production
  script:
    - cd public
    - aws s3 rm s3://$S3_BUCKET/ --recursive
    - aws s3 sync ./ s3://$S3_BUCKET/
    - export AWS_MAX_ATTEMPTS="2"
    - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"
  only:
    refs:
      - main
      - master
